# 02 - Data from the Web

## Deadline
Monday October 17, 2016 at 11:59PM

## Important Notes
* Make sure you push on GitHub your Notebook with all the cells already evaluated (i.e., you don't want your colleagues to generate 
unnecessary Web traffic during the peer review :)
* Don't forget to add a textual description of your thought process, the assumptions you made, and the solution
you plan to implement!
* Please write all your comments in English, and use meaningful variable names in your code

## Background
In this homework we will extract interesting information from [IS-Academia](http://is-academia.epfl.ch/page-6228.html), the educational
portal of EPFL. Specifically, we will focus on the part that allows [public access to academic data](http://is-academia.epfl.ch/publicaccess-Bachelor-Master).
The list of registered students by section and semester is not offered as a downloadable dataset, so you will have to find a way to scrape the
information we need. On [this form](http://isa.epfl.ch/imoniteur_ISAP/%21gedpublicreports.htm?ww_i_reportmodel=133685247) you can select
the data to download based on different criteria (e.g., year, semester, etc.)

You are not allowed to download manually all the tables -- rather you have to understand what parameters the server accepts, and
generate accordingly the HTTP requests. For this task, [Postman](https://www.getpostman.com) with the [Interceptor extension](https://www.getpostman.com/docs/capture)
can help you greatly. I recommend you to watch this [brief tutorial](https://www.youtube.com/watch?v=jBjXVrS8nXs&list=PLM-7VG-sgbtD8qBnGeQM5nvlpqB_ktaLZ&autoplay=1)
to understand quickly how to use it.
Your code in the iPython Notebook should not contain any hardcoded URL. To fetch the content from the IS-Academia server,
you can use the [Requests](http://docs.python-requests.org/en/master/) library with a Base URL, but all the other form parameters
should be extracted from the HTML with [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/).
You can choose to download Excel or HTML files -- they both have pros and cons, as you will find out after a quick check. You can also
choose to download data at different granularities (e.g., per semester, per year, etc.) but I recommend you not to download all the data
in one shot because 1) the requests are likely to timeout and 2) we will overload the IS-Academia server.

## Assignment
We will focus exclusively on the academic unit `Informatique`. When asked, select the right [statistical test](http://hamelg.blogspot.ch/2015/11/python-for-data-analysis-part-24.html).

1. Obtain all the data for the Bachelor students, starting from 2007. Keep only the students for which you have an entry for both `Bachelor
semestre 1` and `Bachelor semestre 6`. Compute how many months it took each student to go from the first to the sixth semester. Partition
the data between male and female students, and compute the average -- is the difference in average statistically significant?

2. Perform a similar operation to what described above, this time for Master students. Notice that this data is more tricky, as there are
many missing records in the IS-Academia database. Therefore, try to guess how much time a master student spent at EPFL by at least checking
the distance in months between `Master semestre 1` and `Master semestre 2`. If the `Mineur` field is *not* empty, the student should also
appear registered in `Master semestre 3`. Last but not the least, don't forget to check if the student has an entry also in the `Projet Master`
tables. Once you can handle well this data, compute the "average stay at EPFL" for master students. Now extract all the students with a 
`Spécialisation` and compute the "average stay" per each category of that attribute -- compared to the general average, can you find any
specialization for which the difference in average is statistically significant?

3. *BONUS*: perform the gender-based study also on the Master students, as explained in 1. Use scatterplots to visually identify changes
over time. Plot males and females with different colors -- can you spot different trends that match the results of your statistical tests?

## Getting Data from the Web

### Part 1

> 1. Obtain all the data for the Bachelor students, starting from 2007. Keep only the students for which you have an entry for both `Bachelor semestre 1` and `Bachelor semestre 6`. Compute how many months it took each student to go from the first to the sixth semester. Partition the data between male and female students, and compute the average -- is the difference in average statistically significant?

In [1]:
from bs4 import BeautifulSoup
import pandas as pd 
import requests
from IPython.core.display import display, HTML

Using Postman with the Interceptor extension, we mimicate a manual browsing of the IS-A web form and button pressing in order to understand which requests are actually sent and which ones of them do matter.

We realize that only 1 matters and store its root URL. One example is as below :

### Key-Value storage

We see in the URL that the actual form options are translated into values. So we would like to have a dictionary in order to store form options as keys and their values as values. That page actually stores all of the possible :

In [77]:
KEY_VALUE_URL = "http://isa.epfl.ch/imoniteur_ISAP/!GEDPUBLICREPORTS.filter?ww_i_reportModel=133685247"

In [88]:
with requests.session() as s:
    response = s.get(KEY_VALUE_URL)
    
soup = BeautifulSoup(response.text, 'html.parser')
input_table = soup.find("table", attrs={"id": "format"})  # we want to find <table border="0" id="format">
option_table = soup.find("table", attrs={"id": "filtre"})  # we want to find <table border="0" id="filtre">
mapper = dict()

for inpt in input_table.findAll("input"):  
    try:
        mapper[inpt.text] = inpt["value"]  # <input type="radio" name="ww_i_reportModelXsl" value="133685270" checked>html
    except:
        pass
    
        
for option in option_table.findAll("option"):  # we want to find all options (e.g. <option value="942293">Architecture</option>)
    try:
        mapper[option.text] = int(option["value"])  # append to the dict (e.g. {'Architecture': 942293}) 
    except:  # if values are 'null' just ignore and pass
        pass

In [89]:
mapper

{'2007-2008': 978181,
 '2008-2009': 978187,
 '2009-2010': 978195,
 '2010-2011': 39486325,
 '2011-2012': 123455150,
 '2012-2013': 123456101,
 '2013-2014': 213637754,
 '2014-2015': 213637922,
 '2015-2016': 213638028,
 '2016-2017': 355925344,
 'Architecture': 942293,
 'Bachelor semestre 1': 249108,
 'Bachelor semestre 2': 249114,
 'Bachelor semestre 3': 942155,
 'Bachelor semestre 4': 942163,
 'Bachelor semestre 5': 942120,
 'Bachelor semestre 5b': 2226768,
 'Bachelor semestre 6': 942175,
 'Bachelor semestre 6b': 2226785,
 'Chimie et génie chimique': 246696,
 'Cours de mathématiques spéciales': 943282,
 'EME (EPFL Middle East)': 637841336,
 'Génie civil': 942623,
 'Génie mécanique': 944263,
 'Génie électrique et électronique ': 943936,
 'Humanités digitales': 2054839157,
 'Informatique': 249847,
 'Ingénierie financière': 120623110,
 'Management de la technologie': 946882,
 'Master semestre 1': 2230106,
 'Master semestre 2': 942192,
 'Master semestre 3': 2230128,
 'Master semestre 4': 2230140,
 'Mathématiques': 944590,
 'Microtechnique': 945244,
 'Mineur semestre 1': 2335667,
 'Mineur semestre 2': 2335676,
 'Mise à niveau': 2063602308,
 'Physique': 945571,
 'Projet Master automne': 249127,
 'Projet Master printemps': 3781783,
 'Science et génie des matériaux': 944917,
 "Sciences et ingénierie de l'environnement": 942953,
 'Sciences et technologies du vivant': 945901,
 'Section FCUE': 1574548993,
 'Semestre automne': 953159,
 "Semestre d'automne": 2936286,
 'Semestre de printemps': 2936295,
 'Semestre printemps': 2754553,
 'Stage automne 3ème année': 953137,
 'Stage automne 4ème année': 2226616,
 'Stage printemps 3ème année': 983606,
 'Stage printemps 4ème année': 2226626,
 'Stage printemps master': 2227132,
 'Systèmes de communication': 946228,
 'html': '133685270',
 'xls': '133685271'}

In [137]:
def make_url(FORMAT, UNITE_ACAD, PERIODE_ACAD, PERIODE_PEDAGO, HIVERETE):
    return ("http://isa.epfl.ch/imoniteur_ISAP/!GEDPUBLICREPORTS.html?"
            "ww_x_GPS=-1&"
            "ww_i_reportModel=133685247&"
            "ww_i_reportModelXsl={frmt}&"
            "ww_x_UNITE_ACAD={unite_acad}&"
            "ww_x_PERIODE_ACAD={periode_acad}&"
            "ww_x_PERIODE_PEDAGO={periode_pedago}&"
            "ww_x_HIVERETE={hiverete}").format(frmt=mapper[FORMAT],
                                               unite_acad=mapper[UNITE_ACAD],
                                               periode_acad=mapper[PERIODE_ACAD],
                                               periode_pedago=mapper[PERIODE_PEDAGO],
                                               hiverete=mapper[HIVERETE])

### Parsing HTML

In [211]:
def html_to_df(html_response):
    soup = BeautifulSoup(html_response, 'html.parser')
    table = soup.find("table")
    table_name = table.findAll("tr")[0].text
    table_columns = [t.text for t in table.findAll("tr")[1].findAll("th")]
    table_rows = table.findAll("tr")[3:]
    rows=[]
    for row in table_rows:
        rows.append([entries.text for entries in row.findAll("td")[:-1]])
    table_df = pd.DataFrame(data=rows, columns=table_columns)
    print(table_name)
    table_df["Time"] = table_name
    table_df.head()
    table_df = table_df.reset_index()
    #table_df.columns = ["Time"] + table_columns
    table_df = table_df.set_index(["Time", "Nom Prénom"])
    return table_df

### Put all into one function

In [212]:
def get_df(FORMAT, UNITE_ACAD, PERIODE_ACAD, PERIODE_PEDAGO, HIVERETE):
    url = make_url(FORMAT, UNITE_ACAD, PERIODE_ACAD, PERIODE_PEDAGO, HIVERETE)
    with requests.session() as s:
        html_response = s.get(url).text
    return html_to_df(html_response)

In [214]:
get_df("html", "Informatique", "2013-2014", "Bachelor semestre 5", "Semestre d'automne").head()

Informatique, 2013-2014, Bachelor semestre 5
 (102 ét.)

                                                                                  index  \
Time                                               Nom Prénom
Informatique, 2013-2014, Bachelor semestre 5\n ... Alonso Seisdedos Florian           0
                                                   Beaud Guillaume François Paul      1
                                                   Benhamadi Yassine                  2
                                                   Bennani-Smires Kamil               3
                                                   Berney Léonard                     4

                                                                                  Civilité  \
Time                                               Nom Prénom
Informatique, 2013-2014, Bachelor semestre 5\n ... Alonso Seisdedos Florian       Monsieur
                                                   Beaud Guillaume François Paul  Monsieur
                                                   Benhamadi Yassine              Monsieur
                                                   Bennani-Smires Kamil           Monsieur
                                                   Berney Léonard                 Monsieur

                                                                                 Orientation Bachelor  \
Time                                               Nom Prénom
Informatique, 2013-2014, Bachelor semestre 5\n ... Alonso Seisdedos Florian
                                                   Beaud Guillaume François Paul
                                                   Benhamadi Yassine
                                                   Bennani-Smires Kamil
                                                   Berney Léonard

                                                                                 Orientation Master  \
Time                                               Nom Prénom
Informatique, 2013-2014, Bachelor semestre 5\n ... Alonso Seisdedos Florian
                                                   Beaud Guillaume François Paul
                                                   Benhamadi Yassine
                                                   Bennani-Smires Kamil
                                                   Berney Léonard

                                                                                 Spécialisation  \
Time                                               Nom Prénom
Informatique, 2013-2014, Bachelor semestre 5\n ... Alonso Seisdedos Florian
                                                   Beaud Guillaume François Paul
                                                   Benhamadi Yassine
                                                   Bennani-Smires Kamil
                                                   Berney Léonard

                                                                                 Filière opt.  \
Time                                               Nom Prénom
Informatique, 2013-2014, Bachelor semestre 5\n ... Alonso Seisdedos Florian
                                                   Beaud Guillaume François Paul
                                                   Benhamadi Yassine
                                                   Bennani-Smires Kamil
                                                   Berney Léonard

                                                                                 Mineur  \
Time                                               Nom Prénom
Informatique, 2013-2014, Bachelor semestre 5\n ... Alonso Seisdedos Florian
                                                   Beaud Guillaume François Paul
                                                   Benhamadi Yassine
                                                   Bennani-Smires Kamil
                                                   Berney Léonard

                                                                                   Statut  \
Time                                               Nom Prénom
Informatique, 2013-2014, Bachelor semestre 5\n ... Alonso Seisdedos Florian       Présent
                                                   Beaud Guillaume François Paul  Présent
                                                   Benhamadi Yassine              Présent
                                                   Bennani-Smires Kamil           Présent
                                                   Berney Léonard                 Présent

                                                                                 Type Echange  \
Time                                               Nom Prénom
Informatique, 2013-2014, Bachelor semestre 5\n ... Alonso Seisdedos Florian
                                                   Beaud Guillaume François Paul
                                                   Benhamadi Yassine
                                                   Bennani-Smires Kamil
                                                   Berney Léonard

                                                                                 Ecole Echange  \
Time                                               Nom Prénom
Informatique, 2013-2014, Bachelor semestre 5\n ... Alonso Seisdedos Florian
                                                   Beaud Guillaume François Paul
                                                   Benhamadi Yassine
                                                   Bennani-Smires Kamil
                                                   Berney Léonard

                                                                                 No Sciper
Time                                               Nom Prénom
Informatique, 2013-2014, Bachelor semestre 5\n ... Alonso Seisdedos Florian         215576
                                                   Beaud Guillaume François Paul    212591
                                                   Benhamadi Yassine                185991
                                                   Bennani-Smires Kamil             204958
                                                   Berney Léonard                   206416

Now we want to answer question 1 : append all dataframes of Informatique we can find from 2007 to now.

In [224]:
PERIODE_ACAD_RANGE = ["{year1}-{year2}".format(
        year1=y,
        year2=y+1) for y in range(2007,2016)]

PERIODE_PEGADO_RANGE = ["Bachelor semestre " + str(n) for n in range(1,7)]
HIVERETE_RANGE = ["Semestre d'automne", "Semestre de printemps"]

PERIODE_RANGE = list(zip(["Bachelor semestre " + str(n) for n in range(1,7,2)], ["Semestre d'automne"]*len(range(1,7,2))))
PERIODE_RANGE += list(zip(["Bachelor semestre " + str(n) for n in range(2,7,2)], ["Semestre de printemps"]*len(range(2,7,2))))

total = []
for periode_acad in PERIODE_ACAD_RANGE:
    for (periode_pedago, hiverete) in PERIODE_RANGE:
        df = get_df("html", "Informatique", periode_acad, periode_pedago, hiverete)
        total.append(df)
            
big_df = pd.concat(total)

[('Bachelor semestre 1', "Semestre d'automne"), ('Bachelor semestre 3', "Semestre d'automne"), ('Bachelor semestre 5', "Semestre d'automne"), ('Bachelor semestre 2', 'Semestre de printemps'), ('Bachelor semestre 4', 'Semestre de printemps'), ('Bachelor semestre 6', 'Semestre de printemps')]
Informatique, 2007-2008, Bachelor semestre 1
 (90 ét.)

Informatique, 2007-2008, Bachelor semestre 3
 (50 ét.)

Informatique, 2007-2008, Bachelor semestre 5
 (48 ét.)

Informatique, 2007-2008, Bachelor semestre 2
 (72 ét.)

Informatique, 2007-2008, Bachelor semestre 4
 (48 ét.)

Informatique, 2007-2008, Bachelor semestre 6
 (38 ét.)

Informatique, 2008-2009, Bachelor semestre 1
 (96 ét.)

Informatique, 2008-2009, Bachelor semestre 3
 (53 ét.)

Informatique, 2008-2009, Bachelor semestre 5
 (57 ét.)

Informatique, 2008-2009, Bachelor semestre 2
 (74 ét.)

Informatique, 2008-2009, Bachelor semestre 4
 (51 ét.)

Informatique, 2008-2009, Bachelor semestre 6
 (51 ét.)

Informatique, 2009-2010, Bachelor semestre 1
 (117 ét.)

Informatique, 2009-2010, Bachelor semestre 3
 (54 ét.)

Informatique, 2009-2010, Bachelor semestre 5
 (75 ét.)

Informatique, 2009-2010, Bachelor semestre 2
 (101 ét.)

Informatique, 2009-2010, Bachelor semestre 4
 (52 ét.)

Informatique, 2009-2010, Bachelor semestre 6
 (60 ét.)

Informatique, 2010-2011, Bachelor semestre 1
 (153 ét.)

Informatique, 2010-2011, Bachelor semestre 3
 (51 ét.)

Informatique, 2010-2011, Bachelor semestre 5
 (62 ét.)

Informatique, 2010-2011, Bachelor semestre 2
 (125 ét.)

Informatique, 2010-2011, Bachelor semestre 4
 (51 ét.)

Informatique, 2010-2011, Bachelor semestre 6
 (52 ét.)

Informatique, 2011-2012, Bachelor semestre 1
 (166 ét.)

Informatique, 2011-2012, Bachelor semestre 3
 (77 ét.)

Informatique, 2011-2012, Bachelor semestre 5
 (63 ét.)

Informatique, 2011-2012, Bachelor semestre 2
 (125 ét.)

Informatique, 2011-2012, Bachelor semestre 4
 (75 ét.)

Informatique, 2011-2012, Bachelor semestre 6
 (52 ét.)

Informatique, 2012-2013, Bachelor semestre 1
 (198 ét.)

Informatique, 2012-2013, Bachelor semestre 3
 (75 ét.)

Informatique, 2012-2013, Bachelor semestre 5
 (96 ét.)

Informatique, 2012-2013, Bachelor semestre 2
 (170 ét.)

Informatique, 2012-2013, Bachelor semestre 4
 (70 ét.)

Informatique, 2012-2013, Bachelor semestre 6
 (81 ét.)

Informatique, 2013-2014, Bachelor semestre 1
 (206 ét.)

Informatique, 2013-2014, Bachelor semestre 3
 (114 ét.)

Informatique, 2013-2014, Bachelor semestre 5
 (102 ét.)

Informatique, 2013-2014, Bachelor semestre 2
 (157 ét.)

Informatique, 2013-2014, Bachelor semestre 4
 (111 ét.)

Informatique, 2013-2014, Bachelor semestre 6
 (86 ét.)

Informatique, 2014-2015, Bachelor semestre 1
 (242 ét.)

Informatique, 2014-2015, Bachelor semestre 3
 (81 ét.)

Informatique, 2014-2015, Bachelor semestre 5
 (140 ét.)

Informatique, 2014-2015, Bachelor semestre 2
 (164 ét.)

Informatique, 2014-2015, Bachelor semestre 4
 (81 ét.)

Informatique, 2014-2015, Bachelor semestre 6
 (116 ét.)

Informatique, 2015-2016, Bachelor semestre 1
 (216 ét.)

Informatique, 2015-2016, Bachelor semestre 3
 (92 ét.)

Informatique, 2015-2016, Bachelor semestre 5
 (128 ét.)

Informatique, 2015-2016, Bachelor semestre 2
 (171 ét.)

Informatique, 2015-2016, Bachelor semestre 4
 (89 ét.)

Informatique, 2015-2016, Bachelor semestre 6
 (104 ét.)

In [246]:
big_df = big_df.reset_index()
#big_df = big_df.set_index([""])
#big_df.loc[(big_df["Nom Prénom"] == "Yu Yamashita")]

custom_index = (big_df["Nom Prénom"].str.endswith("Yu Yamashita"))
big_df[custom_index]
#big_df.groupby(["Nom Prénom"]).describe()

ValueError: cannot index with vector containing NA / NaN values

In [265]:
big_df[big_df["No Sciper"] == "173922"]

,No Sciper,Time,Nom Prénom,level_0,index,Civilité,Orientation Bachelor,Orientation Master,Spécialisation,Filière opt.,Mineur,Statut,Type Echange,Ecole Echange
1,173922,"Informatique, 2007-2008, Bachelor semestre 1\n...",Badoud Morgan,1,1,Monsieur,,,,,,Présent,,
192,173922,"Informatique, 2007-2008, Bachelor semestre 2\n...",Badoud Morgan,192,1,Monsieur,,,,,,Présent,,
447,173922,"Informatique, 2008-2009, Bachelor semestre 3\n...",Badoud Morgan,447,1,Monsieur,,,,,,Présent,,
634,173922,"Informatique, 2008-2009, Bachelor semestre 4\n...",Badoud Morgan,634,1,Monsieur,,,,,,Présent,,
907,173922,"Informatique, 2009-2010, Bachelor semestre 5\n...",Badoud Morgan,907,0,Monsieur,,,,,,Présent,,

In [255]:
big_df.head()

,No Sciper,Time,Nom Prénom,level_0,index,Civilité,Orientation Bachelor,Orientation Master,Spécialisation,Filière opt.,Mineur,Statut,Type Echange,Ecole Echange
0,174905,"Informatique, 2007-2008, Bachelor semestre 1\n...",Aubelle Flavien,0,0,Monsieur,,,,,,Présent,,
1,173922,"Informatique, 2007-2008, Bachelor semestre 1\n...",Badoud Morgan,1,1,Monsieur,,,,,,Présent,,
2,179406,"Informatique, 2007-2008, Bachelor semestre 1\n...",Baeriswyl Jonathan,2,2,Monsieur,,,,,,Présent,,
3,179428,"Informatique, 2007-2008, Bachelor semestre 1\n...",Barroco Michael,3,3,Monsieur,,,,,,Présent,,
4,179324,"Informatique, 2007-2008, Bachelor semestre 1\n...",Belfis Nicolas,4,4,Monsieur,,,,,,Présent,,

In [221]:
params = {
    "UNITE_ACAD" : "Informatique",
    "PERIODE_ACAD" : ["{year1} - {year2}".format(
        year1=y,
        year2=y+1) for y in range(2007,2016)],
    "PERIODE_PEDAGO" : ["Bachelor semestre 1", "Bachelor semestre 6"],
    "HIVERETE" : ["Semestre d'automne", "Semestre de printemps"]
        }

## Get the table

Now that we recieve the page with the information, what we want to do is to scrape that information.  
Given the HTML source code, we can find that the table with names etc is contained under the path `frameset/frameset/frame name="principal"/html/table/tbody/`

<img src="html_to_scrape.png" width="80%">